### ISSUE TITLE
Missing fullname in article workflow.

### ISSUE THREAD

**Issue by oguzdemirbasci** [inspirehep/inspirehep#1553]
We don't want this error message to appear. It should be fixed.

``` python
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/workflow/engine.py", line 529, in _process
    self.run_callbacks(callbacks, objects, obj)
  File "/usr/lib/python2.7/site-packages/workflow/engine.py", line 465, in run_callbacks
    indent + 1)
  File "/usr/lib/python2.7/site-packages/workflow/engine.py", line 465, in run_callbacks
    indent + 1)
  File "/usr/lib/python2.7/site-packages/workflow/engine.py", line 481, in run_callbacks
    self.execute_callback(callback_func, obj)
  File "/usr/lib/python2.7/site-packages/workflow/engine.py", line 564, in execute_callback
    callback(obj, self)
  File "/code/inspirehep/modules/workflows/utils/__init__.py", line 148, in _decorator
    res = func(*args, **kwargs)
  File "/code/inspirehep/modules/workflows/tasks/actions.py", line 311, in _validate_record
    reraise(*sys.exc_info())
  File "/code/inspirehep/modules/workflows/tasks/actions.py", line 303, in _validate_record
    validate(obj.data, schema)
  File "/usr/lib/python2.7/site-packages/inspire_schemas/utils.py", line 728, in validate
    format_checker=inspire_format_checker,
  File "/usr/lib/python2.7/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/usr/lib/python2.7/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
ValidationError: u'' is too short

Failed validating u'minLength' in schema[u'properties'][u'references'][u'items'][u'properties'][u'reference'][u'properties'][u'authors'][u'items'][u'properties'][u'full_name']:
    {u'description': u'Should be of the same form as\n:ref:`hep.json#/properties/authors/items/properties/full_name`.\n\n:example: ``Smith, John G.D.``',
     u'minLength': 1,
     u'type': u'string'}

On instance[u'references'][4][u'reference'][u'authors'][1][u'full_name']:
    u''
```

Relevant report on Sentry : https://sentry.inspirehep.net/inspire-prod/next/issues/25155/?query=is%3Aunresolved%20ValidationError

**Comment by michamos** [comment]
the reference builder should probably not create an author in this case.

**Comment by michamos** [comment]
@oguzdemirbasci In these cases it's good to link to sentry, so you don't have to hunt for the event.
