### ISSUE TITLE
Extract references `KeyError: 'source'`

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#2016]
https://inspirehep.net/holdingpen/3107038
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/workflow/engine.py", line 529, in _process
    self.run_callbacks(callbacks, objects, obj)
  File "/usr/lib/python2.7/site-packages/workflow/engine.py", line 481, in run_callbacks
    self.execute_callback(callback_func, obj)
  File "/usr/lib/python2.7/site-packages/workflow/engine.py", line 564, in execute_callback
    callback(obj, self)
  File "/code/inspirehep/modules/workflows/utils/__init__.py", line 154, in _decorator
    res = func(*args, **kwargs)
  File "/code/inspirehep/modules/workflows/tasks/actions.py", line 471, in refextract
    extracted_raw_references = dedupe_list(extract_references_from_raw_refs(obj.data['references']))
  File "/code/inspirehep/modules/workflows/utils/__init__.py", line 224, in wrapper
    return func(*args, **kwargs)
  File "/code/inspirehep/modules/workflows/utils/__init__.py", line 254, in wrapper
    return timeout(timeout_time, use_signals=use_signals)(func)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/timeout_decorator/timeout_decorator.py", line 81, in new_function
    return function(*args, **kwargs)
  File "/code/inspirehep/modules/workflows/tasks/refextract.py", line 155, in extract_references_from_raw_refs
    extract_references_from_raw_ref(ref, custom_kbs_file=custom_kbs_file) for ref in references
  File "/code/inspirehep/modules/workflows/tasks/refextract.py", line 155, in <genexpr>
    extract_references_from_raw_ref(ref, custom_kbs_file=custom_kbs_file) for ref in references
  File "/code/inspirehep/modules/workflows/tasks/refextract.py", line 195, in extract_references_from_raw_ref
    raw_ref['value'], source=raw_ref['source'], custom_kbs_file=custom_kbs_file
KeyError: 'source'
```

**Comment by MJedr** [comment]
**TECH**

Since [`extract_references_from_text` doesn't require source](https://github.com/inspirehep/inspire-next/blob/05d450a66e2140d5e48c8115d562bec7d816f6fd/inspirehep/modules/workflows/tasks/refextract.py#L126) (and it's not required by schema too) we should change in [here](https://github.com/inspirehep/inspire-next/blob/05d450a66e2140d5e48c8115d562bec7d816f6fd/inspirehep/modules/workflows/tasks/refextract.py#L195) `source=raw_ref['source']` to `source=raw_ref.get('source')`
